version: "3"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 99.98.0.0/16

services:
  bsc_mainnet:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bsc_mainnet
    hostname: bsc_mainnet
    restart: unless-stopped
    ports:
      - "8575:8575"
      - "8547:8547" # Websocket
      - "8576:8576"
      - "8577:8577"
      - "30311:30311/udp"
      - "30311:30311"
    volumes:
      - $PWD/data/mainnet/:/root/.ethereum/
      # - $PWD/config/mainnet/config.toml:/config.toml
    stop_signal: SIGINT
    stop_grace_period: 2m
    command:
      - "geth"
      - "--datadir"
      - "/root/.ethereum/"
      - "--config"
      - "/config.toml"
      - "--syncmode"
      - "full"
      - "--cache"
      - "8000"
      - "--rpc.allow-unprotected-txs"
      - "--txlookuplimit"
      - "0"
      - "--tries-verify-mode"
      - "none"
      - "--diffblock"
      - "5000"
      - "--ethstats"
      - "binance-smart-chain-node:bscpwd@99.98.0.1:3000"
      - "--pruneancient"
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"

  bsc_testnet:
    image: zinnionlcc/bsc_geth
    container_name: bsc_testnet
    hostname: bsc_testnet
    restart: unless-stopped
    ports:
      - "7575:8575"
      - "7547:8547" # Websocket
      - "7576:8576"
      - "7577:8577"
      - "20311:30311/udp"
      - "20311:30311"
    volumes:
      - ./data/testnet/:/root/.ethereum/
      - ./config/testnet/config.toml:/config.toml
    stop_signal: SIGINT
    stop_grace_period: 2m
    command:
      - bsc
      - --nousb
      - --syncmode
      - full
      - --gcmode
      - archive
      - --nousb
      - --cache
      - "8192"
      - --maxpeers
      - "100"
      - --pprof
      - --rpc
      - --rpcaddr
      - "0.0.0.0"
      - --rpcvhosts
      - "*"
      - --rpccorsdomain
      - "*"
      - --ws
      - --wsaddr
      - "0.0.0.0"
      - --wsorigins
      - "*"
      - --wsapi
      - eth,net,web3
      - --wsport
      - "8547"
      - --datadir
      - "/root/.ethereum/"
      - --config
      - /config.toml
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
      
  netstats:
    build: ./netstats
    ports:
      - 3000:3000
    environment:
      WS_SECRET: bscpwd
    restart: always